language: node_js
node_js:
  - "0.10"

services:
  - mongodb

notifications:
  irc:
    channels:
      - "irc.freenode.org#periodicjs"
    on_success: always
    on_failure: always
    template:
      - "Build by %{author} has failed:"
      - "Git Info: %{branch} - %{commit}"
      - "Travis states: %{message}"
      - "Build Details: %{build_url}"
      - "Change View: %{compare_url}"
      skip_join: true

install: 
  - npm install --prefix ./
  - sleep 10
  - npm run postinstall

branches:
  only:
    - master
    - devel
git:
  submodules: false  
